name: Run Postman Collection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  newman-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Newman and htmlextra
      run:
        npm install -g newman
    - name: Install htmlextra
      run:
        npm install -g newman-reporter-htmlextra

    - name: Run Postman Collection with htmlextra reporter
      run: newman run RestFullBooker.postman_collection.json -r htmlextra --reporter-htmlextra-export ./results/report.html

    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: postman-report
        path: ./results/report.html
